//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RRWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [Core.System]
        ///Paths=../../../Engine/Content
        ///Paths=%GAMEDIR%Content
        ///Paths=../../../Engine/Plugins/2D/Paper2D/Content
        ///Paths=../../../Engine/Plugins/Animation/ControlRigSpline/Content
        ///Paths=../../../Engine/Plugins/Animation/ControlRig/Content
        ///Paths=../../../Engine/Plugins/Animation/IKRig/Content
        ///Paths=../../../Engine/Plugins/Animation/MotionWarping/Content
        ///Paths=../../../Engine/Plugins/Bridge/Content
        ///Paths=../../../Engine/Plugins/Compositing/Composure/Content
        ///Paths=../../../Engine/Plugins/Compositing [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MZ����@HVLV�@n��fV�5���9��u�^ɸ��,V��i�Skﺋ���������3�$�0˪��sx��P��#�DTO@���p&amp;K���TQm
        ///΋���Ty��������(�qh�捕�8�,�Ξ��X�xw��PELe��f�(&lt;,\�P,@I��A@��A:��E:�Cf�@h-G,��9T@ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string steamcmd {
            get {
                return ResourceManager.GetString("steamcmd", resourceCulture);
            }
        }
    }
}
